version: '3'
services:
  lab:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./:/mnt
    entrypoint:
      [
        "bash",
        "-c",
        "cd /mnt && jupyter lab  --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash",
      ]
    stdin_open: true
    container_name: "jupyter_lab"
